title: Leonardo Molero # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Estudante de Ciência de Dados
  <br><br>
  Entusiasta de TI
  <br><br>
<a href="www.linkedin.com/in/leonardo-molero">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0
