title: Leonardo Molero 
logo: "/images/logo.png?raw=true"
description: >
  Estudante de Ciência de Dados
  <br><br>
  Entusiasta de TI
  <br><br>
  <a href="www.linkedin.com/in/leonardo-molero">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0
